package com.study.str;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.List;

public class MakeSql {

    public static void main(String[] args) {

        List<String> brands = Arrays
            .asList("0100bychaosfromundermind", "032c", "090factory", "1000v", "100percent",
                "108seoul", "1159studio", "134mm", "13blues", "13month", "13percent", "14studio",
                "1507", "1537", "18hour", "1993studio", "1mmchan", "1newbrandtest", "1soft",
                "210x297", "235laboratory", "2365", "247seoul", "25percentage", "261eui", "2cube",
                "2mod", "2monkey", "2ndesign", "2ndf", "2ndlife", "2pjt", "2xu", "320showroom",
                "33musement", "377place", "38comeoncommon", "407haus", "40oznyc", "47brand",
                "4deaworks", "4dimension", "4t2nd", "4xr", "511tactical", "5252byoioi", "60brix",
                "69slam", "6ft", "6mask", "726gears", "762design", "79by79", "7uniom", "803studio",
                "86road", "8cc", "8division", "8seconds", "a2age", "aaa", "aaawomens", "abaeterno",
                "abbeyhorn", "abcde", "abercrombieandfitch", "abercrombiefitch", "abiruz",
                "abitmor", "abnormalthing", "abonne", "aboutembro", "abrahammoon", "abya",
                "acapulcogold", "accare", "aceout", "acha", "achio", "acho", "acidblack",
                "aciddslide", "ackermann", "aclown", "acme888", "acmedelavie", "acnestudio", "acoc",
                "acoldwall", "acontentslab", "acotedemoi", "acover", "actualpain", "acud",
                "adamsheadwear", "add", "addoff", "addon", "ade", "adhoc", "adidas",
                "adidasshoecare", "adidasunderwear", "adidaswatch", "adle", "adnee", "adore",
                "adoy", "adren", "advisory", "aecawhite", "aeiou", "aekki", "aer",
                "aerographervane", "age", "agedgray", "agender", "agentpeek", "agentpeekreverse",
                "agentprovocateur", "aging", "agl", "agloww", "agnel", "agnesbeyewear", "ahava",
                "ahni", "ahoh", "ahoramovement", "aight", "aiiight", "aintcrack", "aiou", "aippo",
                "airound", "airpunch", "airwalk", "ajobyajofinklabel", "ajobyajooriginallabel",
                "akan", "akecii", "akiiiclassic", "akiyoru", "akok", "akurtz", "al", "alabel",
                "alainn", "alba", "aldobrue", "aldung", "alesm", "aletasandal", "alexandermcqueen",
                "alibenson", "alicemartha", "alland", "allclassic", "alleno", "allkangdesignstudio",
                "allmylips", "almostblue", "alors", "alphaindustries", "alpharuxion", "altamont",
                "although", "alvieromartini1aclasse", "amberjack", "ambitionem", "ambler",
                "amellie", "ameno", "amente", "americanapparel", "americanoptical",
                "americantourister", "amesworldwide", "ameyewear", "amioseoul", "amoebaculture",
                "among", "amonmovement", "amour", "amukorea", "anaelle", "analogmood", "and08",
                "andar", "andblank", "andbutton", "anderssonbell", "anderssonbellforwomen",
                "andneeds", "andr", "andrewco", "andseeyou", "andtheother", "andz", "anello",
                "angeblanc", "angelobianco", "angelsocks", "angeodor", "angmoo", "animate", "anker",
                "annasui", "annc", "anneearchive", "anni", "annspaper", "anoblir", "anodds",
                "anolorcode", "anomiecomplex", "anonimoa", "anonymous", "anormal", "anothera",
                "anotherbridge", "anotherdayofsun", "anotherframe", "anotherlounge",
                "anotheroffice", "anotherone", "anotherplanet", "anotheryouth", "anothing",
                "ansmiel", "answer19", "antepost", "antihero", "antisocialsocialclub", "antler",
                "antlercarrier", "antonymorato", "anymemes", "aoemq", "aott", "apapercut",
                "apartment", "apc", "aphrose", "apoc", "apocofanfare", "apolis", "apparelxit",
                "applendip", "appndxx", "april77", "apto", "aptodelujo", "aqostudiospace",
                "aqumarin", "aquwire", "arac9", "aram", "araree", "arcadecode", "archivepke",
                "archivments", "arco", "arcopedico", "arcteryx", "ardentvellona", "ardorobe",
                "arenabalssam", "arete", "arethat", "areuban", "argo", "arkadius", "arkkcopenhagen",
                "arkon", "armaniexchange", "armaniunderwear", "armo", "armorlux", "arno",
                "aromatica", "around", "around80", "arrange", "arscontact", "artenostudio",
                "artifacts", "artistwear", "artlable", "artti", "arttitude", "arvv", "ash",
                "ashcroft", "asics", "asiha", "asobu", "asolution", "aspivot", "astep",
                "astralprojection", "asura", "atailor", "atar", "atease", "atelierpark", "atempo",
                "athenadesign", "athlete", "athlinablue", "athplatform", "athru", "atmoments",
                "atomic138", "attentionrow", "atthemoment", "atwoodrope", "aubedej", "aucovet",
                "audreyandyoung", "aufstand", "august9", "augustasportswear", "augustharmony",
                "aum89", "aurorashoe", "autourdumonde", "autre", "avamolli", "avan", "avan1",
                "avec", "avecattie", "avecvous", "avenoir", "avoirne", "avventura", "avviso",
                "awco", "awebornus", "awesomedew", "axxstudio", "ayaya", "ayc", "ayiholiccashmere",
                "azero", "baal", "baan", "babletwo", "babycentaur", "babyg", "badblood", "badee",
                "badfactory", "badinbad", "baekya", "baeminstore", "bagall", "baggu", "bagtobasics",
                "bakesole", "balancewood", "balansa", "balant", "balcony", "balenciaga", "ballop",
                "ballute", "bally", "balmain", "banada", "bananafit", "banasilshop", "banc",
                "bando", "bangers", "bants", "bape", "baracca", "barber501", "barbour", "barigate",
                "barrel", "basedonyouth", "basemoment", "basiccotton", "basicelle", "basqueteast",
                "bass", "bassclef", "bassohomme", "baust", "bbc", "bbdesolid", "bbyb",
                "beanpoleaccessory", "beanpoleladies", "beanpolemen", "beanpolesport", "beautisel",
                "beautyinus", "bebello", "beblaze", "bebof", "becabell", "becool", "bedford11th",
                "befriendmarket", "being", "beioff", "beipril", "belier", "bellebeau", "belleffa",
                "bellief", "bellroy", "bemighty", "bemusemasion", "bemymood", "bendavis",
                "benetton", "benfix", "bensimon", "bensimoneyewear", "beready", "beslow",
                "besloworiginals", "beslowpurple", "beslowstandard", "bestdon", "betgures", "betow",
                "betters", "betterthan88", "betweenaandb", "beyerdynamic", "beyondcloset",
                "beyondclosetcollectionlin", "bframe", "bgberlin", "biarritz", "bibyseob",
                "bicycletrophy", "biel", "biensur", "bienvetu", "biflapper", "bigunion",
                "bigwavecollective", "billingham", "billions", "billy8", "bimble", "binnie",
                "birkenstock", "biscuitshop", "bizarrejewelry", "bjegob", "bjewel", "bkermin",
                "blackade", "blackblond", "blackdiamond", "blackhind", "blackhoody", "blackmamba",
                "blackmartinesitbon", "blackmonster", "blacknothing", "blackroses", "blackscale",
                "blacksheep", "blacxyohanix", "blaim", "blak", "blakoon", "blakspace", "blancblack",
                "blancdenoirs", "blanchet", "blank", "blank03", "blankroom", "blcbrand",
                "bledition", "bleh", "blend", "blendednoise", "blendoff", "blessbell",
                "blessedbullet", "blindness", "blkwd", "blond9", "bloomstudio", "blowind",
                "bluebaguette", "blueelephant", "bluefactory", "blueleaf", "blueloungemaestro",
                "blueover", "bluepeach", "bluepie", "bluevine", "bluey", "bluff", "bluv",
                "bmsfrance", "bodyblue", "bodyholic", "bohemianblue", "bolife", "bolla", "bonbeau",
                "bonehead", "bonesoul", "boniee", "bonnechance", "bonnieblanche", "boody",
                "bookonthepark", "boosticsupply", "bornchamps", "bose", "bossbyhugoboss",
                "bostanten", "bottegaveneta", "bouclier", "boundrip", "bowlloon", "bowls",
                "boxandcox", "boxy", "boylondon", "boylondonwatch", "bpack", "bpb", "bpbclub",
                "bracti", "bradipo", "brador", "bradybag", "brahmane", "branded", "brassboats",
                "braun", "bravado", "breda", "breezyexcursion", "brenson", "brianberry", "brick",
                "brisco", "briston", "broandtips", "brogueandmorrow", "broister", "bronomad",
                "bronson", "brooks", "broshpomade", "browend", "brownbreath", "brownpeanut", "brtc",
                "bruman", "brusher", "brute", "bsqtbyclassy", "bsrabbit", "bt21", "bubilian",
                "bubp", "buckaroo", "bucket", "builford", "bulgakov", "bund", "bunkerbuster",
                "burberry", "buriedalive", "burning", "butdeep", "buttero", "buttonseoul",
                "buttonworks", "bvb", "bvheyewear", "bvlgari", "byallmins", "byc", "byebyall",
                "byedit", "byeuuns", "byl", "bymoss", "byroem", "bystandard", "bywpeyewear",
                "cabinzero", "caiman", "californiaproject", "californiarepublic", "calvinklein",
                "calvinkleineyewear", "calvinkleinjeans", "calvinkleinjeansfootwear",
                "calvinkleinperformance", "calvinkleinunderwear", "cambridgesatchel", "camelwork",
                "cameupon", "caminostreet", "camouflagelab", "campers", "campside", "candylabtoys",
                "candyshop", "canebros", "canleap", "captainbanana", "carenology95", "cargo",
                "cargobros", "carhartt", "carharttwip", "caribee", "carin", "carven", "caselogic",
                "casio", "casioedifice", "casperjohnaiver", "caterpillarwatch", "cattline",
                "cccproject", "ceand", "celderma", "celdermadaily", "celebratewithus", "celecon",
                "celine", "cellapy", "cerealand", "cesti", "chaco", "chaenewyork", "chambros",
                "champion", "chancechance", "changeischance", "chaps", "chaptereight", "charico",
                "charms", "chasecult", "chav", "chertoiseoul", "chestofnautilus", "chezjoey",
                "childisharchive", "chinatownmarket", "chindown", "chiquita", "chloe", "choisi",
                "choomsun", "chorrd", "chouettesape", "chrisbrown", "chrischristy", "christiandior",
                "christianlouboutin", "christineproject", "chubasco", "chuck", "chums",
                "ciecamaschera", "cielonda", "cilocala", "circusboyband", "citizen", "citybreeze",
                "civilregime", "claco", "clapiel", "clarks", "classico", "clatage", "clato",
                "claxclo", "clayong", "claysmith", "clean", "clet", "clevermove", "clicclac",
                "clif", "clio", "cloi", "clomor", "clotty", "clove", "clovis", "clriden", "clrotte",
                "clsc", "cluse", "clutstudio", "cnshop", "coach", "coagment", "coal", "coastwonder",
                "cococityboys", "codegraphy", "codeh", "codeholic", "codeim",
                "codenameloolapalooza", "codeofbad", "codescombine", "codescombineinnerwear",
                "codigallery", "cogu", "cokie", "collabotory", "collagevacance", "colleve",
                "collonil", "colorcolla", "colorroad", "colorznewyork", "columbia", "come", "comfy",
                "commed723", "commedesgarcons", "commongarment", "commonlabel", "commonprojects",
                "commonsense", "commonstd", "comodo", "comoninoz", "compagno", "comporta",
                "comsonnot", "comspace1980", "conamor", "conatt", "concent12", "concepts1one",
                "conceptual", "concreat", "concreate", "condor", "conectx", "conichiwabonjour",
                "conocidojeen", "conspara", "controbanal3", "contstudio", "converse", "conveyg",
                "convoy", "coodgear", "cookery", "coopy", "coor", "copychu", "coq", "coquad",
                "coquetstudio", "coralique", "corca", "corci", "corco", "corebridge",
                "cornercolumn", "cornsox", "corotts", "cosmology", "cosrx", "costumeoclock",
                "coteacote", "cotta", "coucou", "countrypowder", "coupdegrace", "cove", "covernat",
                "covers", "coy", "cozycomma", "cp1", "cpcompany", "crank", "crapeyewear",
                "crashbaggage", "creamslab", "creamystudio", "creepstreet", "creima", "crepprotect",
                "crib", "critic", "crocs", "cronous", "crookscastles", "crossavenue",
                "crosscurrent", "crshr", "crump", "crystalkei", "cubeme", "cueclyp", "curb",
                "curetty", "current", "curvo", "custage", "customade", "customellow", "customus",
                "cyaarvo", "d9reserve", "daanhaus", "dadasupreme", "daejoongso", "dael", "dailyinn",
                "dakstowel", "dal", "daleaf", "damagemnemonic", "damp", "danaburton", "danahan",
                "danha", "dansoon", "dantrol", "darkstar", "dashu", "dasom", "dauspice", "davidoff",
                "davidstone", "daydare", "daylife", "daymellow", "dayoff", "daytrip", "dazedayz",
                "dbydgnak", "dccomics", "dclip", "dcraft", "dcshoes", "dcult", "de12look",
                "deadend", "dealersny", "deardictators", "deargarden", "dearme", "dearpeer",
                "dearstalker", "dearyu", "deathlens", "debb", "debell", "decke", "decky", "decolor",
                "default", "defayeblack", "defond", "dejouet", "delalune", "delidi", "delightpool",
                "delilium", "dellastella", "delsey", "deluxbomba", "demaker", "demarc", "demartini",
                "demonade", "demonstrate", "denage", "denham", "denimindigomaster", "denmade",
                "dennyfield", "denote", "departure", "depascal", "dereklam10crosby", "derrohe",
                "descente", "deshana", "designbytss", "designerinvitation", "designskin",
                "designunited", "desmaman", "desxxve", "deumeuand", "deusexmachina", "deutero",
                "deverrman", "deviwear", "dewedewe", "deweheartdewe", "dexxter", "dfleur", "dgre",
                "dhill", "diadora", "diafvine", "diagonal", "diamondlayla", "dickies", "diems",
                "diephod", "diesel", "dieselunderwear", "differentbutsame", "differentisok",
                "diipn", "dimecres", "diminishedseventhchords", "dimitriblack", "dimplit", "dior",
                "diorhomme", "discoveryexpedition", "disney", "disny", "dissizit", "dissorthat",
                "distancer", "ditole", "dizi", "dkny", "dktune", "dlab", "dluv", "dman", "dmoment",
                "dmtpstvm", "doffjason", "dogmatic", "doinmathang", "dol", "dolcegabana", "doldol",
                "dolm", "dolphin", "domba", "dominant", "donkie", "donnakarannewyork",
                "dontforgetme", "doof", "dope", "dopeboymagic", "doratore", "dorco", "doris",
                "doubleac", "doubleadrenalinesyndrome", "doublelovers", "doublenang",
                "doublequotes", "doubleu2", "doubteverthing", "doupwn", "dozoh", "dparks",
                "dprique", "dragon", "drawfit", "drawm", "drc", "drdenim", "drepisode", "drewdraw",
                "drfunnest", "drg", "drife", "driftout", "drilleys", "drjacobs", "drjmeelab",
                "drmartens", "droracle", "drps", "drska", "drtie", "drugwithoutsideeffect",
                "drwonder", "drysteppers", "dsquared2", "dsquared2underbeachwear", "dtrt",
                "duckdive", "dufa", "dujes", "dunlop", "dunst", "dupont", "duran", "dustylab",
                "dvergr", "dvsnstudios", "dwmu", "dxoh", "dyby", "dyclez", "dynafit", "earlstudio",
                "earpearp", "earthus", "earthwell", "ease", "easeoff", "eastindigo", "eastland",
                "eastpak", "easybusy", "easymue", "easypeasy", "eauclair", "ebbetsfield",
                "eberlestock", "ebichu", "ecoroo", "ecru", "edhardyeyewear", "edition", "efeld",
                "egarden", "egotrip", "eider", "eien29", "eightvolume", "einen", "eit", "ejnolee",
                "ekan", "ekhon", "elago", "elbategev", "elcanto", "eleph", "elitesurvivalsystem",
                "elizabeth", "elizabetharden", "ellesse", "elleswimwear", "ellioti", "ellonarc",
                "elm", "elyona", "embizione", "emcoriginalgarments", "emerica", "emerson", "emm",
                "emotionplanet", "emporioarmani", "emptlabel", "enalloid", "encemoment", "endymion",
                "enjoi", "enor", "enou", "enoughisenough", "enthusia", "entrereves", "enzoblues",
                "eone", "eots", "eoustudio", "ephe", "epic", "epicsode", "epos", "es", "escstudio",
                "esfai", "esn", "espionage", "esr", "etnies", "etniesgirls", "etre", "etreseoul",
                "etro", "etsba", "eum", "everki", "everlast", "everwhatever", "excelsior",
                "exotics", "expiredgirl", "extraordinary", "exyaiw", "eyebyeye", "eyelucy", "eyeye",
                "ezio", "ezioshirt", "ezkaton", "ezraarthur", "ezystudio", "fabrik", "fabrixlamp",
                "facefactory", "facetion", "fakemama", "fakeme", "fakerseoul", "famacollection",
                "famigo", "famoussas", "famulus", "fanacult", "fangoh", "fantasticgeneration",
                "fasciera", "fastle", "fatalism", "fatbelly", "fauxpasparis", "favtempo", "favv",
                "fayri", "fbyihm", "fce", "fcmm", "fdm", "fed3", "feed1234", "feelenuff", "feiyue",
                "feldapotheke", "fellas1932", "feltics", "femanish", "fendi", "fennec", "fernshoes",
                "fevertime", "ffai", "fff", "fflow", "fibber41", "fieldmanual", "fieldworker",
                "fifilapin", "fila", "filaeyewear", "fille", "fillike", "fillintheblank",
                "filluminate", "filobisknot", "filson", "fimafia", "findkapoor", "finndgscope",
                "fiore", "fipilock", "firenzeatelier", "firenzehomme", "firstbuck", "firstfloor",
                "firstlight", "fit2c", "fitflop", "fitty", "fivedeck", "fixbinding", "fjallraven",
                "flagship", "flamelmd", "flareup", "flaseek", "flask", "flasttic",
                "flatapartmentcircle", "flatfitty", "flavors", "fleecemelbourne", "flexin",
                "flexxion", "flion", "flirt", "flood", "flopop", "flordeman", "floribus",
                "floridaticket", "flot", "flowford", "fluffy", "fluxperi", "flxbl", "flyingcoffin",
                "flyingninety", "flyrunway", "flyye", "fm9102", "fobene", "foce", "focelady",
                "foceps", "foellie", "fogbow", "folderlabel", "fonderia", "forchaser",
                "foreverybari", "formelcamele", "fossa", "fourcomma", "fourthk", "foyer",
                "fp142muji", "frameby", "framehunt", "frankdominic", "frankenmono",
                "frankymousefamily", "fray", "freakishbuilding", "freaks", "freaksandgeeks",
                "frederickpanny", "fredericm", "fredperry", "freefingers", "freewill", "frei",
                "freiheit", "freiknock", "freka", "freshantiyouth", "freshiam", "fridaymidnight",
                "frizmworks", "frj", "froid", "fromb", "fromchoice", "fromhence", "frommark",
                "fromtheyesterday", "fromwhere", "front2line", "fruitoftheloom", "ftc", "ftlw",
                "ftp", "fuckingawesome", "fullsteam", "fundamentalist", "funeather", "funfromfun",
                "funkihusk", "funkycoco", "fusella", "fuza", "fuzz", "fyuchr", "gabriellee", "gac",
                "gachi", "gachion", "gafh", "gainsboro", "gakka2", "gakuro", "galaxy", "gamtanbra",
                "ganekounit", "ganisong", "gap", "garcontimide", "garmentlable", "garnir", "garo",
                "gathering", "gaze", "gbhapparel", "gcut", "gear3bysaen", "geekers",
                "geektaeyewear", "geeky", "gelatofactory", "generalfinale", "generalideastandard",
                "generalworks", "genglemayhem", "gensdevien", "gentlemensconcept",
                "gentlemenshardware", "gentleproject", "genzie", "georgesband", "geox",
                "gestaltproject", "gflat", "giannilupo", "gieger", "giftoriginal", "gigl", "gildan",
                "gimmetheyoung", "gingereyewear", "gisellina", "giussanitessuti", "givenchy",
                "glamgm", "glasshaus", "globe", "gloryarden", "glostern", "glothesstudio",
                "glotoob", "gloverall", "glowloudey", "glowmonster", "gluck", "gluire", "glyph",
                "goal", "gobi", "gocori", "godbless", "gola", "golaclassics", "goldenai",
                "goldengoose", "goldenpet", "goldpercent", "golfwang", "gomawo", "gonak",
                "gongapron", "gongbaek", "gongjin", "goodal", "gooday", "goodhemp", "goodlifeworks",
                "goodnation", "goodnightdave", "goodnightexpress", "goodwood", "googimscompany",
                "googongfast", "gooseberrylay", "gostreet", "gothicque", "gotravel", "gozer", "gpd",
                "grabin", "gradejewelry", "graenh", "grafen", "grafikplastic", "grafikus",
                "graindebeaute", "gram", "gramicci", "grandeline", "grandvision", "graphplatform",
                "graver", "gravevault", "grayb", "grayhue", "graymelin", "graynoise", "gre1scale",
                "greatoff", "greedilous", "greenery", "greenstuff", "gregory", "greyant", "greyf",
                "greyground", "greyyang", "grimstad", "griptok", "grish", "grooverhyme",
                "grossinventory", "groundwork", "grunland", "gshock", "gucci", "guernseywoollens",
                "guess", "guesswatch", "guilf", "gungho", "gunslip", "gusitu", "gymmaster",
                "haberdashery", "hackesch", "hackish", "hagahi", "haharchive", "hakkablacks",
                "halbkreis", "haleineshop", "hamilton", "hance", "hander", "handsinthepocket",
                "hanryang", "hanssem", "hanyul", "happening", "happeninheaven", "happybath",
                "hardinglane", "harliek", "haruta", "has", "hashtag9", "hater", "hatstory", "hau",
                "hauthomme", "haveagoodtime", "havehad", "haveless", "havism", "havit", "hawha",
                "haz", "hazard4", "hazzys", "hazzysmenrule429", "hbb", "hconnect", "hdcr", "hds",
                "head", "headrang", "headwraps", "healground", "heartclub", "heath",
                "heavenlyjelly", "heavensense", "heavyculture", "heedimensional", "heegui",
                "heelys", "heenn", "heichblade", "heimin", "helement", "helinox", "helldorado",
                "helloboy", "hellocell", "hellvn", "hem", "hennesvaror", "henrycottons", "hera",
                "herculesunderwear", "herisson", "herno", "heronpreston", "herringbone", "herschel",
                "hevitz", "heydude", "heyhidy", "heymisstata", "hfdd", "hiddenforestmarket", "hide",
                "hideout", "hieretdemain", "hififnk", "highcheeks", "highplanet", "highresolution",
                "highschooldisco", "highsierra", "hippytree", "hitec", "hmm", "hoboken",
                "hochdienen", "holidayouterwear", "hollyloveslove", "hollysatuns", "holynumber7",
                "holzpuppe", "homboigoing", "homfem", "honeybrain", "honeyflamingo", "hongshot",
                "horlisun", "hoshihime", "hotdew", "houndville", "houseof1817", "hover", "howear",
                "howl", "howlpot", "howthere", "hoxton", "hstry", "huf", "hugobossunder",
                "humangallery", "hummel", "hupot", "hushucosmetic", "husky", "hutsandbay",
                "hybernat", "hybition", "hydeandwolf", "hyojinoriko", "hyperdenim", "hyperops",
                "i4p", "iamnotahumanbeing", "icegardena508", "ichiny", "icimi", "iconography",
                "ideaend", "idealformen", "idealitic", "igloves", "ihatemonday", "ihnomuhnit",
                "iines", "iise", "ilcorso", "ilio", "illesteva", "illiyoon", "ilovenewyork",
                "iloveugly", "ilyand", "imbtfl", "imei", "imirk", "imperialmotion", "ina", "incase",
                "indep", "independent", "indieslow", "ines", "infacelook", "inflation",
                "injiactive", "inmypark", "innercityaudio", "innisfree", "innoddcent", "innolayer",
                "innovator", "innstant", "inovia", "inprep", "inratiolab", "inrows", "insanegene",
                "insilence", "instance", "instantfunk", "instyle", "intar", "intempomood",
                "interbreed", "intersection", "inthepeople", "inthestar", "invicta", "invisible",
                "iope", "iottie", "ipanema", "iphoria", "iris", "iroas", "ironromeo", "ironyporno",
                "ironypornowhiteline", "isabelmarant", "isbim", "islandslipper", "isoflx",
                "isseymiyake", "issuenumber", "istkunst", "iter", "itkuna", "itsaboutdetail",
                "itsbag", "itsean", "itsskin", "iugamakaras", "ix9", "ixvi", "izipizi", "izola",
                "izro", "jacknicklaus", "jadegoldnine", "jaimeblanc", "jainsong", "jalansriwijaya",
                "jaldoencase", "jamaivu", "jambangee", "jamesdean", "jamiewander", "jamt",
                "jangbbijju", "jansport", "jasonmarkk", "jbansclassic", "jbw", "jchung", "jdaul",
                "jeanpaulgaultier", "jeasher", "jedekonnen", "jeep", "jemkins", "jemut",
                "jenesaisquoi", "jenne", "jenner", "jenniferlopez", "jenniferoom", "jeonbell",
                "jerrican", "jerrybag", "jestina", "jeunesse", "jgracelet", "jhonnywest",
                "jillstuarteyewear", "jillstuartnewyorkmen", "jillstuartsportnewyork",
                "jimikoblico", "jindustry", "jinjonjam", "jipsy", "jiu", "jmarknewyork", "jmolls",
                "jmw", "jmy", "johngyu", "johnnycarson", "johnpeters", "johnvarvatos",
                "jorenzcartiess", "josephstacey", "joslounge", "jourdejaju", "joybee", "joymario",
                "joyment", "jplaystudio", "jrium", "jsny", "jtco", "jttest", "juanayoon",
                "juanhomme", "jubiler", "jucyjudy", "judemccall", "juicycouture",
                "juicycoutureperfume", "julius1", "juliycalla", "julyfour", "jumpfrompaper",
                "junafriends", "junbyjunk", "juneheritage", "jupazip", "juroboros", "justmysize",
                "justo", "justsaturday", "jvineyard", "k2", "kailuabay", "kakaofriends",
                "kaldikabas", "kamoto", "kan6312", "kanco", "kaneitei", "kangol", "kangolwatch",
                "kanken", "kappa", "karaway", "karis", "karllagerfeldeyewear", "karllargerfeld",
                "katespade", "katharsis", "katiacho", "katin", "kavka", "kavu", "kawashokunin",
                "keds", "keek", "keemoon", "keen", "keepblack", "keepem", "keinpionier",
                "kellysneakers", "kennethcole", "kennethyoung", "kenzo", "kenzokids", "kerrijade",
                "kerrywoollenmills", "kessler", "kevinshoes", "keybak", "keygear", "keymun",
                "kichwork", "kiday", "kidkid", "kikap", "kilijaro", "killerbee", "kiluckgi",
                "kimmyj", "kimyung", "kindababy", "kinduser", "king", "kingkroach", "kingpoetic",
                "kingvery", "kiranica", "kirsh", "kirshblending", "kirshpocket", "kirshxrcmt",
                "kisjo", "kissnewyork", "kit", "kitschs", "kittybunnypony", "klasse14",
                "klattermusen", "kleankanteen", "kleinesache", "kleman", "klepton", "klipsurban",
                "knd", "knitly", "knitted", "knockershand", "knottology", "kodak", "koimooi",
                "kolca", "koleat", "koloer", "kolok", "kolonsport", "kompaktrecordbar", "konsfero",
                "konus", "koside", "koxa", "kozett", "koznok", "krackathletic", "krooked", "kruchi",
                "ksubi", "kwani", "kway", "kwonseok", "kye", "kyholab", "kyishoo", "kys", "lab101",
                "lab12", "labccin", "labeaunewyork", "labeless", "labodedermafirm", "lacloudnine",
                "lacokanostra", "lacoste", "lacosteeyewear", "ladlab", "ladyvolume", "lafayette",
                "lafillette", "laflorida", "lafudgestore", "lagrazia", "lagunabeachjean", "lahyang",
                "lakai", "lalasalama", "lalingerie", "lambbyd", "lamermamaison", "lamodechief",
                "lancetti", "landj", "laneige", "langsamer", "language", "langversio", "lanvin",
                "lap", "lapartory", "laplage", "lapricala", "lar", "lartigent", "lartigenthomme",
                "lastrada", "latem", "laul", "laulu", "lausanne", "lavantano", "laverie", "layden",
                "layermood", "layerunion", "lazyncrazy", "lazystudio", "le", "le2", "leapling",
                "leata", "leathergoods", "leatherless", "leathersmith", "lechatelard1802", "lecoq",
                "lecordonnier", "lectro", "ledazzle", "lee", "leeenoir", "leeho", "leeseungbin",
                "leesle", "lefenery", "leffamsterdam", "lefino", "legacybone", "legendwalker",
                "leire", "leiur", "leivy", "lemasque", "lemine", "leminuit", "lemme", "lenina",
                "lenoid", "lescolorer", "lespecs", "lessbutbetter", "letqstudio", "lettercomo",
                "letterfrommoon", "lettredeletoile", "leuchtfeuerstrickwaren", "levis", "levou",
                "lewave", "lexis", "leyiel", "lg", "liberclassy", "liberteng", "lieu", "lieul",
                "life", "lifework", "lifla", "liful", "lightplace", "liinta", "likejazz",
                "likelihood", "likerise", "likesomemore", "lilyfit", "linbo", "lincolnframe",
                "linderswiss", "lining", "liquorbrand", "lirik", "lirikos", "lit", "llbean",
                "lloyd", "lmc", "lmn3011", "lmood", "locate", "lockfinger", "locle", "locobasic",
                "lodis", "loeil", "lofi", "lofn", "lohnt", "lojel", "lokche", "lokward",
                "loloatalanta", "lombrillant", "lomheaven", "londontradition", "loner", "longchamp",
                "longplayingrecord", "lonsdale", "lookast", "looking4u", "loomloom", "looseriders",
                "loqi", "lordjohngrey", "loremipsum", "lores", "lostandfound", "lostgarden",
                "lotuff", "louieooie", "louisquatorze", "loupsblancs", "lovecharm", "lovemeback",
                "lovememonster", "lower", "lowt", "loyalfriend", "lsw", "ltck", "luciente",
                "luckycharms", "luckydice", "luckyplanet", "lude", "lueurparis", "luffkingz",
                "luften", "lugz", "luicamong", "luminox", "luna", "lunabeauty", "lunacy",
                "lunasandals", "lunecave", "luoespac", "lup", "luvistrue", "luvistruegirl",
                "luvistruestreet", "luvur", "luwu", "lwl", "lyceenne", "m082", "macarthur",
                "macblacksports", "mackage", "mackay", "mackbarry", "macmoc", "madehanmut",
                "madgoat", "madhippie", "madinly", "madmars", "madn", "maedaryuto", "maedy",
                "magazineb", "magenta", "magforce", "magforceblacklabel", "magicchannel",
                "magicmohican", "magoodgan", "magpierobin", "mahagrid", "mahogani", "mainbooth",
                "maisondeines", "maisondesucre", "maisonkitsune", "maisonmargiela",
                "maisonmartinmargiela", "maisonmined", "majestick", "majofactory", "majournee",
                "maked", "makeitsimple", "makeon", "male24365", "malen", "malibusandals",
                "mallingbooth", "maloja", "malrang", "mamamastudio", "mamonde", "manavis7", "manes",
                "mang", "manhattanpassage", "manhattanportage", "maniamass", "maniepiedi",
                "mannequin", "mannylonq", "manod", "manomos", "manoti", "mansionair",
                "manwithflowers", "manyofactory", "marcatory", "marceloburlon", "marchwith",
                "marciodiego", "marcjacobs", "marcoroho", "mare", "margarinfingers",
                "margesherwood", "marhenj", "marithefrancoisgirbaud", "mark4", "markgonzales",
                "markm", "markmate", "marksman", "markvolume", "marni", "marrt", "marsbom",
                "marsiler", "martenata", "martincoks", "martistique", "marvel", "maryjames",
                "marymond", "maska", "maskitsch", "masmarulez", "massivegroove", "massnoun",
                "mastef", "matchglobe", "mathematik", "matt", "mattnnat", "mauisons",
                "mauvaisgarcons", "mauve", "mauvefantasticever", "maw", "maxmara", "mayteg",
                "maziuntitled", "mazzucato", "mbs", "mccoii", "mccoin", "mcdodo", "mcm", "mcnchips",
                "mdoc", "mdplus", "mechanixwear", "mediheal", "meetmetmeet", "megapack",
                "megaphone", "meieldew", "melangemaster", "melic", "mellowus", "meltinglow",
                "memenmori", "meninjungle", "menipello", "mep", "mercedesbenz", "merken", "merlic",
                "meromero", "merriment", "merrycoop", "merrymotive", "merze", "merzy",
                "messageinthesocks", "metalmulisha", "metapher", "metif", "meumdal", "meverick",
                "mezmic", "mezzokunst", "mfnt", "mglam", "mgmgstudio", "miamiproject",
                "michaelkors", "micks", "midair", "midnightmove", "mignonneuf", "miim", "mik",
                "mikve", "militariapress", "milky", "millet", "milletclassic", "millflat",
                "millibar", "millin", "millionairehats", "millioncor", "millioncormens", "millo",
                "millogrem", "milspecmonkey", "miltonstelle", "mimicawe", "miminko", "mimixiu",
                "mimthewardrobe", "minav", "mindbridge", "mindmaster", "minifocus", "minimalcode",
                "minimalproject", "minos", "mintaretro", "minu", "minus8", "minutte", "mip", "mis",
                "miseenscene", "mishka", "mishuusomuch", "missue", "misterchild", "mistica",
                "misticdun", "mitchellandness", "mitte", "miumiu", "mixxo", "mizu", "mizuno", "mlb",
                "mlbcosmetics", "mlbeyewear", "mlbgroo", "mlimited", "mmam", "mmarker", "mmd",
                "mmgl", "mmic", "mmlg", "mmoustache", "mmroom", "mnii", "mnl", "mnw", "moaa",
                "moart", "mobler", "moccasom", "modelimite", "moderate", "moderment", "modernable",
                "modernstudios", "modgone", "modified", "modnine", "moemore", "mohan", "moimoii",
                "moiqui", "moistudio", "mokuyobi", "mol", "moleskine", "molibdeno", "molingbling",
                "molliolli", "mollive", "momckits", "momentwatches", "momg", "monbric",
                "monchouchou", "moncler", "mondayedition", "mondayhiking", "mongtana",
                "monkeyflower", "monoclothes", "monoflow", "monoflux", "monofold", "monolounge",
                "monomania", "monono", "monopatin", "monotheme", "monotype", "monsterrepublic",
                "monsterrepublicheadwear", "montanawest", "montbell", "montblanc", "montbrun",
                "moo", "moochuu", "moomuua", "moonblue", "mooneed", "moonsward", "moonymoonie",
                "mooseknuckles", "moosim", "moran", "moranyif", "moreas", "morejude", "moreorless",
                "morethandope", "morethanlike", "morl", "moro", "morp", "mosmor", "mosports",
                "motivemascolanza", "motivestreet", "motomoto", "mott", "movinsr", "moyen",
                "mozmoz", "mpg", "mpow", "mrmrs", "mrmustardstudio", "msgm", "mskn2nd", "msms",
                "msolic", "msstest", "msul", "mtm", "mtodesign", "mudern", "mudidi", "muer", "muff",
                "mugio", "muguet", "muhcosmetic", "mujjo", "mukan", "mulawear", "mulberry",
                "mulligan", "mumchit", "munikund", "muninnstation", "munn", "mur", "musebyrose",
                "musee", "museeaart", "musemont", "musinsa", "musinsastandard", "mutement",
                "mutemuse", "muto", "muveclothing", "muzik", "mvio", "mwc", "mwcwatch", "myboo",
                "mysteryranch", "mystique", "nacific", "naguisa", "naisho", "nakedfamous", "nakes",
                "namedshoes", "nameout", "nanacrew", "napapijri", "nar", "narrowmind",
                "nastyfancyclub", "nastyhabit", "nastyhabitcollection", "nastykick", "nastypalm",
                "nationalgeographic", "nationalpublicity", "native", "nativesons", "nau",
                "navadesign", "navy", "navyscandal", "nba", "ncover", "ndearose", "ndozen",
                "near8dear", "neata", "need", "needly", "needmore", "needushop", "neighbors",
                "neikidnis", "neilbarrett", "neonmoon", "nepa", "nerdy", "nettgray", "neufetbleu",
                "neverflow", "newbalance", "newbie", "newhattan", "newkit", "newnow",
                "newyorkhatco", "nextorch", "nfl", "nicknicole", "nidalcashmere", "niger",
                "nightflow", "nii", "nike", "nikeeyewear", "nikegolf", "ninanosano", "ninaricci",
                "ninedollar", "nineeleven", "nineoctopus", "ninetyplus", "nivada", "nivelcrack",
                "nnd", "nnmns", "noart", "noclaim", "node", "nodoubtnoway", "nofficialnoffice",
                "nohant", "noir", "noirer", "noize", "noizycompany", "noknok", "nomad", "nomadic",
                "nomanual", "nomas", "nomination", "nomonico", "nonandnon", "nondisclothes",
                "nonenon", "nonlocal", "nonmainstreamer", "nonseason", "noonoofingers",
                "nopainnosaks", "nopastnofuture", "nordicisland", "normalpeople", "not", "not4nerd",
                "nota", "notabag", "notamo", "nothingisbetterthanme", "notknowing", "notnnot",
                "notus", "notyetguys", "noun", "nouveauandmore", "novelclothes", "novella",
                "novesta", "novio", "nowandtomorrow", "nowwhat", "noycommon", "ntrlhgh", "nuaname",
                "nuavo", "nubes", "nudiejeans", "nuevo", "nukak", "nul", "numberplant",
                "numverstar", "nuparcc", "nuper", "nutandbolt", "nuuygnaseel", "nuvo10", "nybk",
                "oakley", "oart", "oastudio", "obaku", "oberon", "obey", "obg", "object", "obla",
                "obless", "occhidilupo", "oceanpacific", "oct3", "oct31", "oddcollet", "oddeyewear",
                "oddfuture", "oddmood", "oddoneout", "oddstudio", "odyssey", "officialgarment",
                "offroutefest", "offtherecord", "offwhite", "oft", "oganacell", "ogio", "ogotai",
                "ogram", "ohhioh", "ohl", "ohohex", "ohrlin", "ohuuu", "ohverdose", "ohyeah",
                "oiauer", "oilleak", "oioi", "ojeh", "ojos", "okidoki", "olady", "oldiesgoodies",
                "olight", "olivercustom", "olivergoldsmith", "oliverpeoples", "oliviaburton",
                "ollot", "olzen", "ometo", "omgt", "omoojeans", "omoplataa", "ona", "once32",
                "onebrilliant", "oneenough", "onehunnnit", "oneill", "oneinamillion",
                "oneninenineone", "oneoseven", "oneperzero", "onerm", "onlyonce", "onne", "onore",
                "ood", "oofos", "oohahh", "ooparts", "oorrddiinnaarryy", "opticalw", "oralb",
                "orderplease", "ordinaryday", "ordinaryholiday", "ordinarypeople", "ordor",
                "orient", "originalchuck", "originalswat", "orinbe", "oror", "ortlieb", "oryany",
                "oscuro", "osee", "osmo", "ost", "ostkaka", "otherside", "otheruse", "otherworldly",
                "otie", "ottocap", "otz", "oughic", "ouimaisnon", "ouipaname", "ouitt", "our",
                "ourhistory", "ourscope", "ouse", "outdoorproducts", "outdoorresearch", "outmode",
                "outofcircle", "outofhabit", "outofoffice", "outshell", "outstanding", "outxo",
                "ovdy", "overboard", "overcast", "overlab", "overr", "overtheone", "ovrdrv",
                "owl91", "owl91woman", "owner", "ownu", "oxstudios", "oy", "pacificlegend",
                "pacorabanne", "padamview", "painorpleasure", "paintoz", "pairs", "pairwel",
                "palaceskateboards", "paletot", "paletteon", "palladium", "panam", "pandora",
                "pandorafit", "pandorumjewelry", "pantonetravel", "paparecipe", "paperism",
                "paraboot", "parachase", "paracia", "parajumpers", "parfumdefemme", "parker",
                "pars", "partimento", "parts", "partyafterdark", "pascorozen", "pases", "pasotti",
                "pastelcloud", "patrick", "paulhan", "paulhueman", "paulmedison", "paulrevere",
                "paulsboutique", "paulsmith", "paulvice", "pausenbreak", "pavement", "peacebesarah",
                "peacemaker", "peachbanana", "peanuts", "pearlcare", "peeps", "pegador", "pemborke",
                "pemont", "penfield", "peoplefootwear", "pepperseasoning", "perenaido", "peripera",
                "perstep", "petderdllaproject", "peterbag", "peterjensen", "petiful", "pfflyers",
                "pfs", "philippemodel", "philippplein", "philocaly", "phonecklace", "phonophono",
                "phos333", "photon", "pianari", "pianer", "picometer", "pidanstudio", "piecemaker",
                "pieceworker", "pier4", "pierrecardin", "pigandhen", "pigfarmer", "pigles",
                "pigmillion", "pilgrim", "pinblack", "pindex", "pinkpineapple", "piquadro",
                "piscator", "pistilo", "plac", "placement", "plage", "plainworks", "planetremaker",
                "plasmasphere", "plasticproduct", "plateau", "playbye", "playian", "playmonster",
                "playmonstereyewear", "playnomore", "playp", "playtex", "pleasepleaseme",
                "pleatsmama", "plhaming", "plugnplay", "plusminuszero", "pm0617", "pmco", "poa",
                "poane", "pocketpistols", "pocketshot", "poesiedame", "poff", "point", "polar",
                "polham", "police", "polkapolka", "pollution", "poloralphlauren", "ponerbrow",
                "poopourri", "popmartkorea", "popsocket", "poseganch", "poshprojects", "positivev",
                "postlude", "postx", "poszer", "potentstar", "pout", "powertothepeople", "powit",
                "ppp", "prada", "prairie", "predator", "premiata", "premier", "premierfits",
                "premierxflipper", "preparat", "prestons", "prettee", "primaclasse", "primapunta",
                "primauter", "primavera", "primera", "primitive", "proclub", "project624",
                "projectfoce", "projectin", "projectm", "projectvv", "prokeds", "proof", "propper",
                "prospecs", "prouns", "prowowrldcup", "prpl", "psmaryjane", "publicbeacon",
                "publicicon", "publish", "pubtcarrier", "pulmuone", "pulpo", "puma", "pumabodywear",
                "punchline", "punkt", "punpun", "pureheals", "purpleflowers", "purpleocean",
                "qantodeloco", "qaproject", "qcumbers", "qdmm", "qmile", "qsleather", "qt8",
                "quaci", "qualpack", "quantiti", "quarqor", "quavino", "quayeyeware", "quietist",
                "quiksilver", "quisque", "qv", "racy", "radineo", "radios", "raime",
                "rainbowsandals", "rainbowwatch", "raive", "ralmode", "ramolin", "raon",
                "rapiddominance", "raresome", "raskal", "ratfink", "rationnement", "raventears",
                "raveup", "ravide", "raviin", "rawrow", "rawtoraw", "rayshiso", "rckt", "rdc",
                "rdvz", "realcontents", "realeesm", "realization", "rebel8", "reblank", "reclow",
                "redkap", "redkroc", "redmeteordesign", "redwing", "reebok", "reebokunderwear",
                "reedpages", "reflyperky", "reframe", "reiku", "reinamora", "reinaperfume",
                "reindeer", "rekken", "relizmproduct", "remantist", "rendering", "renoma",
                "renomaswim", "reorg", "repetto", "replay", "replaycontainer", "repre", "rerhee",
                "reselect", "reshoevn8r", "respect", "restinpieces", "revedeagneau", "reverco",
                "revereve", "revin", "revineo", "revoirsis", "revolutionglass", "rexy",
                "rhearockin", "ridercommune", "rieti", "rightroute", "rimou", "rinse", "ripndip",
                "risebelow", "ritamonica", "rnot", "roar", "robertadicamerino", "robertjchawaii",
                "roccirocci", "rociety", "rockamerica", "rocketxlunch", "rockfish", "rockingag",
                "rocknfresh", "rockport", "rockpsycho", "rockspring", "rodd", "rohseoul", "roial",
                "roidesrois", "roideter", "roilroil", "rolarola", "rollienation", "rollingstudios",
                "romanson", "romanticcrown", "romanticmove", "romanticmovewoman", "romanticpirates",
                "ronron", "roomu", "roopretelcham", "rootage", "rootote", "rosak",
                "roseapplestudio", "roshoeman", "rosier", "rothco", "rougeblanc", "rougeetlenoir",
                "rougenlounge", "roughneck", "roughside", "roundlab", "rowtique", "roxy",
                "royalhawaiiancreations", "royallife", "royalpiece", "royray", "royroyseoul",
                "rroes", "rs9seoul", "rshemiste", "rsvp", "rubbermaid", "ruckuz", "ruffwear",
                "ruggedhouse", "ruhm", "runds", "runninghigh", "runningnose", "ruonine", "rushoff",
                "russellathletic", "rusticdime", "ruthless", "rwder", "ryake", "ryoo", "ryulwai",
                "rziozia", "sabona", "sac", "sacai", "saesocks", "safehouse", "saii",
                "saintgallery", "saintjames", "saintlaurent", "saintpain", "saintrobe",
                "saintscott", "saintshow", "sakk", "saladbowls", "sallyariel", "salomon",
                "salomonlifestyle", "salondeseoul", "salondeyohn", "salrang", "salvatoreferragamo",
                "salvatos", "sameforts", "samoondoh", "samsonite", "samsonitered", "samsung",
                "samyuk", "sandbox", "sandpiper", "sangsangpowerstation", "sanguine", "sansan",
                "santacruz", "saphir", "sartorresartus", "satorisan", "sattchi", "saturdayeleven",
                "satya", "savage", "saysky", "scaletto", "scalettoblack", "scene", "scenuerdo",
                "schneider", "schottnyc", "schpet", "schwanengarten", "scorpion", "scs",
                "scuderiaferrari", "sculptor", "sealandgear", "seanlip", "seanmakescloth",
                "search410", "sebs", "sec", "secbyrigoon", "secondaily", "secondcorner",
                "seconduniquename", "seconnation", "seesaw", "seiko", "seirus", "seizetheday",
                "sejinist", "sekanskeen", "sekhmet", "selfesteem", "selfish", "selleriastamerra",
                "semicode", "semicoloneyewear", "senselect", "seoki", "seokwoonyoon",
                "seoulapparel", "september29", "september5", "septembernine", "ser", "serigraphie",
                "setsetset", "setupexe", "sevendrops", "sevenselah", "seventeenth", "sewclassic",
                "sewingboundaries", "sexto", "sextonxxline", "sexychampion", "sexyformula", "shaka",
                "shakawear", "sharon6", "sheerk", "shethiscomma", "shinjeo", "shiroineko",
                "shirter", "shobonyata", "shoecus", "shojiami", "shoopen", "shoveoff",
                "shushusassy", "shutter", "sic", "siero", "sierocosmetic", "sigg", "signap",
                "signature", "significant", "silentsociety", "simple", "simplelife", "sinclair",
                "sinkerloop", "sinoon", "sinsneakers", "sisnbro", "siwy", "sixsox", "sixsteps",
                "sixtyseven", "sjyp", "skagen", "skamp", "skatersocks", "skono", "skootapparel",
                "skrap", "skullcandy", "skullpig", "slamode", "sleazycorner", "sleepycat",
                "sleepyslip", "sley", "slow", "slowacid", "slowattention", "sloweing", "slowhuman",
                "slowmove", "slowpoke", "slowservice", "slowuniverse", "slowwatch", "slowwave",
                "smas", "smashoes", "smcl", "smiley", "smith", "smitharmor", "snackculture",
                "snillostitch", "snoopy", "snoozy", "snout", "snowbison", "snowmoon", "snowpeak",
                "soaq", "socksappeal", "sockstaz", "socksthelanguage", "sodamon", "sofreshandclean",
                "softseoul", "softur", "sognareby", "sogonsogon", "solacebydennis", "solelab",
                "soleloop", "sollumeesthe", "somethingacoustic", "soniavia", "sonovesto",
                "sonsofanarchy", "soohyang", "sookoi", "soonplus", "sorrytoomuchlove", "sortie",
                "sosolife", "sott", "soulassassins", "soultosoul", "soumere", "soundsbmuet", "soup",
                "sovermentwithlomort", "sowerium", "soxfit", "soxxsyndrome", "spaceage", "spao",
                "spaver", "specialguest", "sperone", "spettro", "spitfire", "spoche", "sportear",
                "springcrocus", "spunky", "spypaul", "sserpe", "sseyt", "ssoc", "ssqr", "ssrl",
                "ssum", "ssy", "staffonly", "stagename", "stanard", "standardcurve",
                "standoutstore", "standup", "stanleykubrick", "stanray", "starb", "stare",
                "starter", "staticflow", "staygold", "staywithme", "stco", "steady", "steadycomma",
                "steadyeverywear", "stealearth", "stealer", "stealmonster", "steelwheels",
                "stellabe", "stellamccartney", "stellareale", "stereovinyls", "sterlingworth",
                "stigma", "sting925", "stiu", "stockholmsyndrome", "stoe", "stoneisland",
                "stonystride", "storets", "stormempire", "storyus", "straps", "stratic",
                "streetfoot", "streeth", "streetstandard", "stretchangels", "strike", "strongstraw",
                "stscott", "studiog", "studioselmyeot", "studiotomboy", "studiouzu", "stumblin",
                "stumpstudio", "stunt", "stussy", "styleplan", "suadd", "suare", "suatelier", "sub",
                "subet", "suecommabonnie", "suenoa", "sugapoint", "suicidaltendencies", "suicoke",
                "suin", "suitable", "suitsuit", "sullywong", "sundaylounge", "sundayoffclub",
                "sundaysalon", "sundaysomewhere", "sunnus", "sunski", "superbasic",
                "superbyretrosuperfuture", "supercroc", "supercrocaction", "superdry", "superga",
                "superinc", "superlit", "supermoon", "supervision", "supportlight", "supreme",
                "surflifesavingsunscreen", "surrealbutniceunisex", "swagger", "swear", "sweetch",
                "sweetoneeighty", "sweetsoup", "swellmob", "swib", "swissmilitarycarrier",
                "swissmilitaryhanowa", "swissmoncross", "switfish", "swsw", "swummit", "swynes",
                "symboler", "tabletalk", "tackleesearch", "tacs", "tactfulkiosk", "taewoo",
                "tagheuer", "tailorstudio", "takeasy", "takeform", "takewhatyouneed", "takus",
                "tamimstudio", "tandy", "tantan", "targetto", "tasteofessence", "tastystudio",
                "tatasocks", "tatras", "tattist", "tawntoe", "taze", "tdn", "teams", "teamsculptor",
                "teatimeofspring", "techflavor", "techne", "tedbaker", "teeaz", "teethoffice",
                "telic", "tembea", "tenblade", "tener", "tenmore", "tenpoints", "tensor", "tenue",
                "terg", "terranation", "terrywood", "test0316", "test1234", "testa11", "testbinary",
                "teva", "textilearea", "tgn", "thatsit", "thaumatrope", "theabon", "theblackswan",
                "thebluebeardsrevenge", "theboysaredead", "thecentaur", "thechlia", "theclotho",
                "thedef", "thedosi", "theearth", "thefreccia", "thegreatest", "thehermitproject",
                "thehommeloose", "thehundreds", "theinternatiiional", "theklaxon", "theknitcompany",
                "thelogue", "theloom", "thelutin", "themadness", "themann", "themile", "thence",
                "thenorthface", "theperfecthand", "thequietlife", "theroyalwe", "therubz",
                "thesallyslaw", "theshowwasnotover", "theslowinglot", "thesoga", "thespringhome",
                "thestori", "thestudiok", "thetint", "thetshirtmuseum", "theveryoung",
                "theverything", "thewander", "thewanksers", "thewildduck", "thim", "thincker",
                "third", "thirdweave", "thirteen", "thisabled", "thisish", "thisisneverthat",
                "thisrespect", "thomasmore", "thomasvailey", "thombrowne", "thorogood", "thrasher",
                "threads", "threeknocks", "threetoeighty", "thud", "thule", "tibaeg", "tictectoc",
                "tiemeyoung", "tiformen", "tightinspired", "tillidie", "timberland", "timbuk2",
                "timealone", "timeslip", "timex", "tinablossom", "tintinshop", "tipiwear",
                "tiptoppomade", "tissot", "tissuclubband", "tlevel", "tleyoung", "tmoby13month",
                "tmrw", "tngt", "tnp", "toat", "toboggan", "toboog", "tods", "toffee", "tofit",
                "toi", "tomford", "tommyhilfiger", "tommyhilfigerfootwear", "tommyhilfigerwoman",
                "tommyjeans", "tomstoni", "tomtoc", "tomtomorrow", "tonymoly", "tonywack",
                "topsync", "topten", "torso", "toryburch", "tose", "totm", "tottenhamapparel",
                "tou", "touchground", "towbinare", "tracker", "travel", "travel237", "travelmate",
                "travelon", "travs", "treaju", "treatroom", "treign", "trendfactory", "trickers",
                "tridentcase", "trillion", "triop", "triplepam", "triplesens", "trippincell",
                "tripshion", "trisha", "tritone", "triwa", "trmark", "troispoint", "trpcorp",
                "truepenny", "trunkproject", "try", "trytotlak", "tsnine", "ttangbyeolmedley",
                "ttmab", "ttttype", "tugu", "tuk", "tulipalee", "tumi", "tuo", "tustus", "tvobt",
                "twelvesome", "twn", "twonique", "twopack", "twotwootwo", "twvp", "typica", "uag",
                "uandjproject", "ubesco", "ugg", "uglybeaver", "uglyshadow", "uimiga",
                "ujewelscent", "uknowalice", "ulc", "ulkin", "ullalapajamas", "ultimeik", "umbro",
                "umm", "umun", "unalloyed", "unbday", "unboundedawe", "unclockwism", "unclose",
                "uncoated247", "uncommen", "unconstrained", "uncos", "underair", "underarmour",
                "underbase", "undercontrol", "undercontrolstudio", "underlabel", "underyouth",
                "uneri", "unfold", "unhate", "uni", "uniapparel", "uniere", "uniformbridge",
                "uniisdesign", "uniongarments", "unionlow", "unionobject", "unipair",
                "unipoplegwear", "unitbrand", "universalchemistry", "universaloverall", "universo",
                "unlikelook", "unlimit", "unnown", "unother", "untage", "untouched", "upfront",
                "uppercutdeluxe", "upstatestock", "urago", "urangs", "urbandtype", "urbanlike",
                "urbanoriginals", "urbanplayers", "urbanscape", "urbanstoff", "urbanstrikers",
                "urimera", "usamerchandising", "usedfuture", "usite", "usnthem", "uss2", "ust",
                "usualedit", "v2", "vabeu", "valentinogarabani", "valentinorudy", "valextra",
                "valiant", "vanadis", "vanbrough", "vannworks", "vanone", "vanquest", "vans",
                "vantique", "varisonc", "varzar", "vastic", "vatoz", "vdr", "veak", "vector",
                "vector2", "vector3", "vector4", "vector5", "veda", "vegace", "vegantiger", "vei8",
                "veimode", "vemver", "vendetta", "venicate", "venque", "vente", "ventez",
                "ventolation", "verdamt", "veresto", "vermilan", "veronicaforlondon", "verris",
                "versace", "verseone", "vertetnoir", "vertexnextlevel", "vertx", "veryvain",
                "veteze", "vgtb", "viabondevia", "viamonoh", "vibrate", "vicocristallini", "victor",
                "victoriahyde", "viewy", "viinut", "viktorrolfeyewear", "vimun", "vinaj", "vincis",
                "vinedew", "viollina", "visitinnewyork", "vistic", "vital", "vitalsign", "vitaly",
                "vivaclassy", "vivant", "vivastudio", "vive", "vivevive", "viviennewestwood",
                "vlack", "vlado", "vladvlades", "vleeda", "vlndfles", "vogatha", "voiebit",
                "volcom", "volksvagenwatch", "volterra", "voumuiel", "voweler", "vowood", "voyonn",
                "vtcosmetics", "vuiel", "vulcanizer", "vvv", "wabanakki", "wackomaria", "wacoq",
                "wade", "waikei", "wakemeup", "walknrest", "wanderingyouth", "wanggwan", "wannafit",
                "wanton", "wardrobe", "warmlish", "warriorclothing", "watchoutbaby", "wathen",
                "wavegun", "waveunion", "wayway", "waze", "wdressroom", "weallknowit", "wearpanda",
                "weekade", "wefam", "weirdwave", "weksnoop", "welcomerecords", "welder", "welldone",
                "wellmadecom", "wendigo", "wesc", "westcoastchoppers", "westwardcalifornia",
                "wetheroad", "whale2whale", "whateverwewant", "wheelpak", "whenidiff",
                "wheniwasyoung", "whiteproject", "whitesands", "whitetailsjewelry", "whoau",
                "whodings", "wholovesart", "whyrirover", "whysocerealz", "whystyle", "wigglewiggle",
                "wiggys", "wildbricks", "willicot", "willieandduffy", "wilsfabrik", "wishu",
                "wissy", "witholiday", "withtory", "witinart", "wittman", "wkndrs", "wolgan",
                "wolverine", "wonderbra", "wondervisitor", "wonjineffect", "woodbury",
                "woojinplastic", "woong", "woonmu", "wooving", "woozo", "workordance",
                "workspedition", "worldanthemwave", "wrangler", "wrongdirection", "wstandard",
                "wstar", "wundergeist", "wuzustudio", "wvproject", "wwike", "wyse", "xcxmain",
                "xddesign", "xero", "xess", "xlarge", "xmm", "xnaduworks", "xperimnt", "xpier",
                "xs", "xsacky", "xtm", "xtonz", "xyz", "yale", "yase", "yellowstone", "yeomida",
                "yeomim", "yeowoohwajangdae", "yeseasy", "yeseyesee", "yiemmiwaltz", "yignil",
                "yiyoon", "ymclky", "ynotc", "yobs", "yojiyamamoto", "yokomall", "yolokorea",
                "yomon", "yorkminster", "youandmecosmetics", "youneedgarments", "youness",
                "youngandone", "youngsterna", "youngwalljunction", "yourmonthyourday", "youser",
                "youthbath", "yowe", "yoy", "ypydesignstudio", "yragray", "yrn", "yuemai",
                "yuimaru", "yuppe", "yuppie", "yvesga", "yycc", "zadigvoltaire", "zamu", "zanca",
                "zanimal", "zaodam", "zato", "zaxy", "zcolico", "zennycloset", "zerodeconduite",
                "zeroj", "zeroplanet", "zerostreet", "zhouero", "zigdig", "zihee", "ziklag",
                "zimzum", "ziszas", "zizis", "zleyhardi", "zod", "zoggs", "zonphyto", "zplish",
                "zudritt", "zulupack");

        List<Integer> categoryIds = Arrays
            .asList(1,12,16,20,27,28,29,2,3,4,5,6,7,8,9,10,11,13,14,15,17,18,19,21,22,23,24,25,26);


        String query = "insert into brand_category_map (brand_category_id, brand) \nvalues ";

        StringBuffer buffer = new StringBuffer();
        buffer.append(query);

        brands.forEach(brand -> {
            categoryIds.forEach(categoryId -> {
                String addQuery = String.format("\n(%s,\"%s\"),", categoryId, brand);
                buffer.append(addQuery);
            });
        });

        File file = new File("brand_category_map_insert.txt");

        try (FileWriter fileWriter = new FileWriter(file)) {
            PrintWriter printWriter = new PrintWriter(fileWriter);
            printWriter.print(buffer);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
